import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    marginVertical: 20,
  },
  permissionContainer: {
    padding: 20,
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#06b6d4",
    marginVertical: 16,
  },
  permissionText: {
    color: "#67e8f9",
    fontSize: 16,
    marginBottom: 16,
    textAlign: "center",
  },
  cameraContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  camera: {
    flex: 1,
  },
  cameraOverlay: {
    flex: 1,
    backgroundColor: "transparent",
  },
  cameraInstructions: {
    position: "absolute",
    top: 100,
    left: 20,
    right: 20,
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
    padding: 16,
    borderRadius: 12,
  },
  cameraButtonContainer: {
    position: "absolute",
    bottom: 40,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  closeButton: {
    backgroundColor: "rgba(239,68,68,0.9)",
    borderRadius: 50,
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#ef4444",
  },
  captureButton: {
    backgroundColor: "rgba(6,182,212,0.9)",
    borderRadius: 50,
    width: 80,
    height: 80,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#06b6d4",
  },
  captureButtonInner: {
    backgroundColor: "rgba(6,182,212,1)",
    borderRadius: 35,
    width: 70,
    height: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  captureButtonText: {
    fontSize: 24,
    color: "white",
  },
  flipButton: {
    backgroundColor: "rgba(0,0,0,0.7)",
    borderRadius: 50,
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#6b7280",
  },
  actionButton: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 6,
    marginVertical: 8,
    alignItems: "center",
  },
  cameraButton: {
    backgroundColor: "#06b6d4",
    borderColor: "rgba(6,182,212,0.5)",
  },
  galleryButton: {
    backgroundColor: "#8b5cf6",
    borderColor: "rgba(139,92,246,0.5)",
  },
  actionButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  button: {
    backgroundColor: "#06b6d4",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 6,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
});

export default styles;